import type { Metadata } from 'next'
import { Inter, Questrial, Syne } from 'next/font/google'
import './globals.css'
import NavBar from './(home)/components/NavBar'

// const inter = Inter({ subsets: ['latin'] })
// const syne = Syne({ subsets: ['latin'] })
// const questrial = Questrial({ subsets: ['latin']})


const syne = Syne({ subsets: ['latin'], variable:'--font-syne', weight: ['400','500', '700'] })
const questrial = Questrial({ subsets: ['latin'], variable:'--font-questrial', weight: ['400'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${syne.variable} ${questrial.variable}`}>
        {children}
      </body>
    </html>
  )
}
